In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [12]:
a.dtype

dtype('int64')

In [14]:
b.dtype

dtype('float64')

In [15]:
aa = np.array([1,2,3], dtype='int16')

In [16]:
aa.dtype

dtype('int16')

In [28]:
a_size = a.itemsize
aa_size = aa.itemsize
f"A size of a array: {a_size} and a size of aa array: {aa_size}"

'A size of a array: 8 and a size of aa array: 2'

In [38]:
a_total_size = a.size * a.itemsize # a.size to liczba elementów listy
aa_total_size = aa.size * aa.itemsize
print(a_total_size)
print(aa_total_size)

24
6


In [31]:
print(a.nbytes) # size * itemsize
print(aa.nbytes)

24
6


In [59]:
a =np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [57]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [61]:
a[1,5] # element: 13

13

In [63]:
a[0, :] # wiersz 1

array([1, 2, 3, 4, 5, 6, 7])

In [64]:
a[:, 2] # kolumna 3

array([ 3, 10])

In [68]:
a[0, 1:6:2] # [startindex:endindex:stepsize]

array([2, 4, 6])

In [71]:
a[0, 1:-1:2]

array([2, 4, 6])

In [76]:
a[1,5] = 20 # zamiana elementu 13 na 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [93]:
a[:, 2] =[30, 333]
print(a)

[[  1   2  30   4   5   6   7]
 [  8   9 333  11  12  20  14]]


In [106]:
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]]) # 3-d array, shape: 2x2x2
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [104]:
c.shape

(2, 2, 2)

In [105]:
c[0,1,1] # getting element 4

4

In [125]:
d = np.array([[[1,2,3], [4,5,6,], [7,8,9]], 
               [[10,11,12], [13,14,15], [16,17,18]], 
               [[19,20,21], [22,23,24], [25,26,27]]], dtype='int16') # 3-d array, shape: 3x3x3
print(d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [126]:
d.shape

(3, 3, 3)

In [127]:
d.size

27

In [128]:
d.itemsize

2

In [129]:
d.dtype

dtype('int16')

In [130]:
d.ndim

3

In [131]:
d.nbytes

54

In [134]:
# geting line 16,17,18
d[1, 2, :]

array([16, 17, 18], dtype=int16)

In [136]:
# getting column 19,22,25

In [138]:
d[2, :, 0]

array([19, 22, 25], dtype=int16)

In [163]:
e = d[:, 1, :]
e

array([[ 4,  5,  6],
       [13, 14, 15],
       [22, 23, 24]], dtype=int16)

In [169]:
d[:, 1, :] = [[99,99,99], [99,99,99], [99,99,99]] # replacing 

In [168]:
d

array([[[ 1,  2,  3],
        [99, 99, 99],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [99, 99, 99],
        [16, 17, 18]],

       [[19, 20, 21],
        [99, 99, 99],
        [25, 26, 27]]], dtype=int16)

In [171]:
# all zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [173]:
np.zeros((3,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [175]:
# all ones
np.ones((3,3), dtype='int16')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [180]:
# Any other number FULL
np.full((3,3), 99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [181]:
# Any other number FULL LIKE
np.full_like(a, 44)

array([[44, 44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44, 44]])

In [182]:
# Random dcimal numbers
np.random.rand(2,3)

array([[0.81133175, 0.83204702, 0.8323523 ],
       [0.47732688, 0.49282251, 0.11674382]])

In [192]:
# Random integer values
np.random.randint(-4,8, size=(2,3))

array([[-4,  7, -1],
       [ 7,  4, -3]])

In [193]:
# Identity
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [199]:
# repeating 
arr = np.array([[1,2,3]])
b1 = np.repeat(arr, 4, axis=0)
print(b1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [211]:
output = np.ones((5,5), dtype='int16')
print(output)

zeros = np.zeros((3,3), dtype='int16')
zeros[1,1] = 9
print(zeros)

output[1:4,1:4]=zeros
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### copying arrays

In [215]:
bb = np.array([1,2,3])
print(bb)

[1 2 3]


In [217]:
cc = bb.copy()
print(cc)

[1 2 3]


In [218]:
cc[1] = 200
print(cc)
print(bb)

[  1 200   3]
[1 2 3]


### Mathematics

In [267]:
a = np.array([1,2,3,4], dtype='int16')
print(a)

[1 2 3 4]


In [268]:
a.dtype

dtype('int16')

In [248]:
a + 2
print(a + 2)

[3 4 5 6]


In [249]:
a += 2
print(a)

[3 4 5 6]


In [253]:
a - 2

array([-1,  0,  1,  2])

In [255]:
a * 2

array([2, 4, 6, 8])

In [257]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [258]:
b = np.array([1,0,1,0])

In [259]:
a + b

array([2, 2, 4, 4])

In [269]:
c = a ** 2

In [270]:
c

array([ 1,  4,  9, 16], dtype=int16)

In [271]:
c.dtype

dtype('int16')

In [273]:
np.sin(a)

array([ 0.84147096,  0.9092974 ,  0.14112   , -0.7568025 ], dtype=float32)

In [274]:
np.cos(a)

array([ 0.5403023 , -0.41614684, -0.9899925 , -0.6536436 ], dtype=float32)

### Linear Algebra

In [280]:
x = np.ones((2,3))
print(x)
y = np.full((3,2), 2)
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [284]:
np.matmul(x, y) # mnożenie macierzy

array([[6., 6.],
       [6., 6.]])

In [288]:
c = np.identity(3)
print(c)
np.linalg.det(c) # wyznacznik macierzy jednostkowej C

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

### Statistics

In [289]:
stats = np.array([[1,2,3], [4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [292]:
np.min(stats)

1

In [295]:
np.min(stats, axis=0)

array([1, 2, 3])

In [294]:
np.min(stats, axis=1)

array([1, 4])

In [291]:
np.max(stats)

6

In [296]:
np.sum(stats)

21

In [297]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [298]:
np.sum(stats, axis=1)

array([ 6, 15])

### Reorganizing

In [299]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [311]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [314]:
# verticaly stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [319]:
# horizontal stacing vectors
np.hstack((v1, v2, v2, v2)) # działa z () oraz []

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8])

### różne

In [334]:
filedata = np.genfromtxt('data.txt', delimiter=',') # loading data from file txt
filedata = filedata.astype('int32') # zamiany typu danych
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [335]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [339]:
sample = filedata[filedata > 50]
print(sample)

[196  75 766  75  55 999  78  76  88]


In [340]:
sample

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [343]:
sample[[1,3,8]]

array([75, 75, 88], dtype=int32)